apiVersion: faas.redhat.com/v1alpha1
kind: JSFunction
metadata:
  name: testfunc
spec:
  # Add fields here
  func: | 
    const http = require('http');
    const port = 8181;

    const handler = (request, response) => {
      console.log(request.url);
      response.end('Hello Node.js Function!');
    };

    const server = http.createServer(handler);

    server.listen(port, (err) => {
      if (err) {
        return console.log('something bad happened', err);
      }

      console.log(`server is listening on ${port}`)
    });
